#!/usr/local/bin/bash

#########################################
# THIS SECTION !!SHOULD NOT!! BE MODIFIED BY
# DEVELOPERS AS IT PROVIDES COMMON FUNCTIONS
# FOR ALL KINDS OF SCRIPTS
#
# Maintainer: Edison Guo <hydra1983@gmail.com>
#########################################
# Resolve Script Base
function _script_base() {
    local script_base script_name

    if [[ -L $0 ]] ; then
        script_base=$(cd $(dirname $(readlink -f $0)); pwd)
    else
        script_base=$(cd $(dirname $0); pwd)
    fi

    script_name=$(basename $0)

    if [[ -d "${script_base}/../share/${script_name}" ]]; then
        script_base="$(cd ${script_base}/../share/${script_name}; pwd)"
    fi

    echo "${script_base}"
}

# Load Dependencies
[ -f "$(_script_base)/_index.sh" ] && \
    chmod +x "$(_script_base)/_index.sh" && \
    "$(_script_base)/_index.sh" "$(_script_base)" || \
    true
#########################################

#api: ### `_trace`
function _trace () {
  shlog -l 'trace' $1
}

#api: ### `_debug`
function _debug () {
  shlog -l 'debug' $1
}

#api: ### `_info`
function _info () {
  shlog -l 'info' $1
}

#api: ### `_warn`
function _warn () {
  shlog -l 'warn' $1
}

#api: ### `_error`
function _error () {
  shlog -l 'error' $1
}

#api: ### `_assert`
function _assert () {
  local expression="$1"
  local message="$2"
  local lineno="$3"

  local result=$(eval "test ${expression}" && echo "true")

  if [ "${result}" != "true" ]
  then
    if [[ ! -z "${message}" ]]; then
      local msg="${message}"
    fi

    if [[ ! -z "${lineno}" ]]; then
      local msg="${msg} '[File] $0@$lineno'"
    fi

    _error "${msg}"

    exit 1
  # else
  #   return
  #   and continue executing the script.
  fi
}
