#!/usr/local/bin/bash

#========================================
# Load Dependencies
#========================================
__load "${BASH_SOURCE[0]}" "shcolorizer"
__load "${BASH_SOURCE[0]}" "shlog"

#api: ### `_trace`
function _trace () {
  shlog -l 'trace' "$1"
}

#api: ### `_debug`
function _debug () {
  shlog -l 'debug' "$1"
}

#api: ### `_info`
function _info () {
  shlog -l 'info' "$1"
}

#api: ### `_warn`
function _warn () {
  shlog -l 'warn' "$1"
}

#api: ### `_error`
function _error () {
  shlog -l 'error' "$1"
}

export -f _trace
export -f _debug
export -f _info
export -f _warn
export -f _error
