#!/usr/local/bin/bash

#========================================
# Load Dependencies
#========================================
__load "${BASH_SOURCE[0]}" "shcolorizer"
__load "${BASH_SOURCE[0]}" "shlog"

#api: ### `_trace`
function _trace () {
  shlog -l 'trace' "$1"
}

#api: ### `_debug`
function _debug () {
  shlog -l 'debug' "$1"
}

#api: ### `_info`
function _info () {
  shlog -l 'info' "$1"
}

#api: ### `_warn`
function _warn () {
  shlog -l 'warn' "$1"
}

#api: ### `_error`
function _error () {
  shlog -l 'error' "$1"
}

#api: ### `_assert`
function _assert () {
  local expression="$1"
  local message="$2"
  local lineno="$3"
  local result
  
  result=$(eval "test ${expression}" && echo "true")

  if [ "${result}" != "true" ]
  then
    if [[ ! -z "${message}" ]]; then
      local msg="${message}"
    fi

    if [[ ! -z "${lineno}" ]]; then
      local msg="${msg} '[File] $0@$lineno'"
    fi

    _error "${msg}"

    exit 1
  # else
  #   return
  #   and continue executing the script.
  fi
}
